EVICEcreate database MLTP

go

use MLTP

go

create table MLTP_USER
(
ID int identity primary key,
USERNAME NVARCHAR (200),
NAME NVARCHAR (200),
SURNAME NVARCHAR (200),
EMAIL NVARCHAR (200),
PASSWORD NVARCHAR (200),
GSM NVARCHAR (200)
)

GO

CREATE TABLE MLTP_ROLE
(
ID int identity primary key,
NAME NVARCHAR (200),
DESCRIPTION NVARCHAR (200)
)

GO

CREATE TABLE MLTP_USER_ROLE
(
ID int identity primary key,
USER_ID int references MLTP_USER (ID),
ROLE_ID int references MLTP_ROLE (ID)
)

GO

CREATE TABLE MLTP_MENU
(
ID int identity primary key,
DISPLAY_NAME NVARCHAR (200),
PARENT_MENU_ID INT,
ICON NVARCHAR (200),
RECORD_STATUS_ID INT
)

GO

CREATE TABLE MLTP_ROLE_MENU
(
ID int identity primary key,
ROLE_ID INT REFERENCES MLTP_USER_ROLE (ID),
MENU_ID INT REFERENCES MLTP_MENU (ID)
)

GO

CREATE TABLE MLTP_USER_DEVICE
(
ID int identity primary key,
USER_ID int references MLTP_USER (ID),
APP_ID NVARCHAR(200),
PHONE_MODEL NVARCHAR(200) ,
PHONE_VERSION NVARCHAR(200) ,
PLATFORM NVARCHAR(200),
CREATE_DATE DATETIME  
)
